{% set version = "1.1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-diffdf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/diffdf_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/diffdf/diffdf_{{ version }}.tar.gz
  sha256: 5c2e5f76092ce6e7619dbcda23e44210dbfbd380ab2500242ecf67d33b5248ad

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-assertthat
    - r-tibble
  run:
    - r-base
    - r-assertthat
    - r-tibble

test:
  commands:
    - $R -e "library('diffdf')"           # [not win]
    - "\"%R%\" -e \"library('diffdf')\""  # [win]

about:
  home: https://gowerc.github.io/diffdf/, https://github.com/gowerc/diffdf/
  license: MIT
  summary: Functions for comparing two data.frames against each other. The core functionality is to provide a detailed breakdown of any differences between two data.frames as well as providing utility functions to help narrow down the source of problems and differences.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
